# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consecutiveconsumemission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='consecutiveconsumemission',
            name='targetCategory',
        ),
        migrations.RemoveField(
            model_name='consecutiveloginmission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='mealmission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='randommission',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='randommission',
            name='targetItem',
        ),
        migrations.DeleteModel(
            name='ConsecutiveConsumeMission',
        ),
        migrations.DeleteModel(
            name='ConsecutiveLoginMission',
        ),
        migrations.DeleteModel(
            name='MealMission',
        ),
        migrations.DeleteModel(
            name='Missions',
        ),
        migrations.DeleteModel(
            name='RandomMission',
        ),
    ]
