# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='hp',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user_monster',
            name='current_hp',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
