# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_auto_20160820_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutiveConsumeMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=0, max_digits=4)),
                ('required_days', models.DecimalField(decimal_places=0, max_digits=4)),
                ('exp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConsecutiveLoginMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=0, max_digits=4)),
                ('required_days', models.DecimalField(decimal_places=0, max_digits=4)),
                ('exp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MealMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=20)),
                ('exp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missionType', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charge.User')),
            ],
        ),
        migrations.CreateModel(
            name='RandomMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('expiredTime', models.DateTimeField(blank=True)),
                ('exp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charge.Missions')),
                ('targetItem', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Item')),
            ],
        ),
        migrations.AddField(
            model_name='mealmission',
            name='mission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Missions'),
        ),
        migrations.AddField(
            model_name='consecutiveloginmission',
            name='mission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Missions'),
        ),
        migrations.AddField(
            model_name='consecutiveconsumemission',
            name='mission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Missions'),
        ),
        migrations.AddField(
            model_name='consecutiveconsumemission',
            name='targetCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Category'),
        ),
    ]
