# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0002_auto_20160820_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='name',
            field=models.CharField(default='Boss', max_length=100),
        ),
        migrations.AlterField(
            model_name='monster',
            name='exp',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='monster',
            name='money',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
