# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_auto_20160820_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutiveBudgetMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DecimalField(decimal_places=0, max_digits=4)),
                ('required_days', models.DecimalField(decimal_places=0, max_digits=4)),
                ('budget', models.DecimalField(decimal_places=0, max_digits=8)),
                ('exp', models.DecimalField(decimal_places=0, max_digits=10)),
                ('money', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mission', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.Missions')),
            ],
        ),
    ]
