# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_auto_20160820_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pngFile',
            field=models.CharField(default='', max_length=200),
        ),
    ]
