# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0004_consecutivebudgetmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='missionType',
            field=models.CharField(max_length=40),
        ),
    ]
