# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0007_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consecutiveconsumemission',
            name='days',
        ),
        migrations.RemoveField(
            model_name='consecutiveconsumemission',
            name='required_days',
        ),
        migrations.AddField(
            model_name='consecutiveconsumemission',
            name='currentConsume',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consecutiveconsumemission',
            name='expiredTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='consecutiveconsumemission',
            name='requiredConsume',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mealmission',
            name='expiredTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
