# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0008_auto_20160820_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutivebudgetmission',
            name='accumulation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
